
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: postgres
  # password: doctor
  
development:
  <<: *default
  database: doctor_appointment_api_development

test:
  <<: *default
  database: doctor_appointment_api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>