default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  database:  doctors_appointment_development

test:
  <<: *default
  database:  doctors_appointment_test

production:
  <<: *default
  database:  doctors_appointment_production
  username:  doctors_appointment
  password: <%= ENV["DOCTORS_APPOINTMENT_DATABASE_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>
